checks:
    php:
        code_rating: true
        duplication: true

build:
    tests:
        override:
            -
                command: './bin/phpunit'

filter:
    paths: ["src"]
    excluded_paths:
        - "spec/"
        - "tests/"
