checks:
    php:
        code_rating: true
        duplication: true

build:
    tests:
        override:
            -
                command: './bin/phpunit'
    environment:
        php:
            version: '7.0'

filter:
    paths: ["src"]
    excluded_paths:
        - "spec/"
        - "tests/"
