checks:
    php:
        code_rating: true
        duplication: true

build:
    tests:
        override:
            -
                command: './bin/phpspec run -fpretty && ./bin/phpunit --coverage-clover=clover.xml; if [ "$?" -gt "2" ]; then exit 1; fi'
                coverage:
                    file: 'clover.xml'
                    format: 'php-clover'
    environment:
        php:
            version: '7.1'

filter:
    paths: ["src"]
    excluded_paths:
        - "spec/"
        - "tests/"
